### ISSUE TITLE
Kanban - React Group Project

### ISSUE THREAD

**Issue by HectorTorresE** [HectorTorresE/Space-Travelers-Hub#25]
The project's link: [Project Kanban](https://github.com/HectorTorresE/Space-Travelers-Hub/projects/1)

in this project, the group consists of 2 team members @HectorTorresE  and @JuanLPalacios

**Comment by prolajumokeoni** [comment]
Hi Team 👋🏿 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
